name: skeleton
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  drift: ^2.15.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  sqlite3_flutter_libs: ^0.5.19+1
  path_provider: ^2.1.2
  path: ^1.8.3
  sqlite3: ^2.3.0

dev_dependencies: 
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  rename: ^3.0.1

flutter: 
  uses-material-design: true
  assets:
    - assets/

